#!/bin/bash
export SUPABASE_URL="https://rcgynwcttgvqcnbyfhiz.supabase.co"
export SUPABASE_KEY="sb_publishable_DGjAbWbzmEo7yqEOibia0A_r9mWOu-W"

insert_opp() {
  local json="$1"
  local title=$(echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])" 2>/dev/null)
  
  # Check for duplicate first
  local encoded_title=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$title'))" 2>/dev/null)
  local existing=$(curl -s "${SUPABASE_URL}/rest/v1/opportunities?select=id,title&title=eq.${encoded_title}" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Accept: application/json")
  
  if echo "$existing" | python3 -c "import sys,json; d=json.load(sys.stdin); exit(0 if len(d)>0 else 1)" 2>/dev/null; then
    echo "⏭ SKIPPED (duplicate): $title"
    return
  fi
  
  local http_code=$(curl -s -o /tmp/sb_resp.json -w "%{http_code}" \
    "${SUPABASE_URL}/rest/v1/opportunities" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=representation" \
    -H "Accept: application/json" \
    -d "$json")
  if [ "$http_code" = "201" ]; then
    local new_id=$(cat /tmp/sb_resp.json | python3 -c "import sys,json; print(json.load(sys.stdin)[0]['id'])" 2>/dev/null)
    echo "✓ ID $new_id: $title"
  else
    echo "✗ FAILED: $title (HTTP $http_code)"
    cat /tmp/sb_resp.json 2>/dev/null
    echo
  fi
}

echo "=== Inserting medium-priority FRA opportunities (March 16, 2026) ==="
echo "=== 8 new listings + 1 existing entry update ==="
echo

# 1. Annecy MIFA Pitches
insert_opp '{"title":"ANNECY MIFA PITCHES (International Animation Film Market)","What Is It?":"The Annecy International Animation Film Festival, held annually in June in Annecy, France, is the world'"'"'s largest and most prestigious animation event. MIFA (Marché International du Film d'"'"'Animation) is the festival'"'"'s dedicated industry market, bringing together animation studios, distributors, broadcasters, and investors from around the world. MIFA Pitches allow selected projects to present to international buyers and financiers across four categories. African animation is experiencing rapid growth, with studios like Triggerfish (South Africa), Kugali (Nigeria), and others producing content for Netflix, Disney+, and other global platforms. MIFA is where the global animation industry does business.","For Films or Series?":"Animation only — feature films, TV series, short films, transmedia, and immersive/VR projects. Four pitch categories at MIFA.","What Do You Get If Selected?":"Live pitch to international animation buyers, broadcasters, distributors, and investors. Access to the full MIFA market floor and networking events. Visibility in the world'"'"'s largest animation industry gathering.","Cost":"Accreditation fee for MIFA market access. Pitch submissions may have separate deadlines.","Next Deadline":"Annual, June. Annecy 2026 registration open. Check annecy.org for MIFA Pitch submission dates.","Apply:":"annecyfestival.com","Who Can Apply / Eligibility":"Animation studios, producers, and creators globally. Projects must be animation (any format).","What to Submit":"Project pitch package as specified per MIFA Pitch category. Details on the Annecy Festival website.","Strongest Submission Tips":"African animation is one of the fastest-growing segments of the continent'"'"'s creative industries. If you are an African animation studio or creator, MIFA is the single most important market to attend. Triggerfish (Kizazi Moto, Mama K'"'"'s Team 4) and Kugali (Iwaju with Disney) have demonstrated that African animation can reach global audiences. Use MIFA to connect with international co-producers and distributors. Pair with the ACP-EU Culture Programme (in this guide) for co-production financing.","CALENDAR REMINDER:":"Annecy 2026: June, Annecy, France. Register early for MIFA Pitches.","status":"approved","votes":0}'

echo

# 2. DISCOP
insert_opp '{"title":"DISCOP (Pan-African Content Market)","What Is It?":"DISCOP is a pan-African content market that connects content distributors and producers with acquisition and co-production executives through curated virtual and in-person meetings. Founded by Basic Lead, DISCOP has historically operated markets in Johannesburg and Abidjan (Ivory Coast), making it one of the longest-running dedicated African content trading platforms. The market focuses on content distribution — connecting sellers of finished content with African and international broadcasters, OTT platforms, and digital distributors. DISCOP also includes a co-production forum and training programmes. While the market has evolved from primarily in-person to include virtual components, it remains a significant platform for African content trading.","For Films or Series?":"All formats — television series, feature films, documentaries, formats, and digital content. Focus on finished content distribution and licensing.","What Do You Get If Selected?":"Pre-arranged one-to-one meetings with content buyers and distributors. Access to the co-production forum. Networking with African and international content professionals. Training programme access.","Cost":"Registration fee applies. Various delegate categories.","Next Deadline":"Check discop.com for upcoming market dates and registration.","Apply:":"discop.com","Who Can Apply / Eligibility":"Content distributors, producers, broadcasters, OTT platforms, and acquisition executives. Focus on African and international content professionals.","What to Submit":"Delegate registration via the DISCOP website. Content sellers should prepare screeners and sales materials.","Strongest Submission Tips":"DISCOP is particularly valuable for content that is ready for distribution — finished series, films, and formats seeking African broadcast partners. If you have completed content and want to reach African broadcasters and OTT platforms, DISCOP provides targeted matchmaking. Combined with MIP Africa (October, Cape Town) and the Durban FilmMart (July, Durban), DISCOP adds another touchpoint in the African content market calendar.","CALENDAR REMINDER:":"Check discop.com for upcoming market dates.","status":"approved","votes":0}'

echo

# 3. Carthage Film Festival (JCC)
insert_opp '{"title":"CARTHAGE FILM FESTIVAL — JCC (Journées Cinématographiques de Carthage)","What Is It?":"The Carthage Film Festival (Journées Cinématographiques de Carthage, or JCC) is the oldest film festival in both Africa and the Arab world, founded in Tunis, Tunisia in 1966. Initially biennial, it became annual in 2014. The 36th edition took place in December 2025. JCC is dedicated to cinema from the Arab world, Africa, and the Global South, with competitive sections for feature films, documentaries, and short films. The Tanit d'"'"'Or (Golden Tanit) is the festival'"'"'s top prize. JCC also runs Takmil, a post-production support programme for Arab and African films. The festival is a critical platform for Francophone and North African filmmakers, complementing Marrakech (already in this guide) and FESPACO (also in this guide).","For Films or Series?":"Feature fiction, documentary, short films. Competition for films from Africa, the Arab world, and the Global South.","What Do You Get If Selected?":"Festival screening and awards eligibility including the Tanit d'"'"'Or (Golden Tanit). Networking with North African and Arab film industry professionals. Access to the Takmil post-production support programme. Visibility across the Francophone African and Arab film ecosystem.","Cost":"Submission via FilmFreeway (fees may apply)","Next Deadline":"JCC 2026 expected December 2026, Tunis, Tunisia. Watch jcctunisie.org for call for submissions.","Apply:":"jcctunisie.org","Who Can Apply / Eligibility":"Filmmakers from Africa, the Arab world, and the Global South. Films must be recent productions.","What to Submit":"Completed film via the JCC submission platform or FilmFreeway.","Strongest Submission Tips":"JCC is essential for Francophone African and North African filmmakers. It is the oldest film festival on both the African and Arab continents, and selection carries significant prestige. The Takmil post-production programme is particularly valuable for filmmakers who need finishing funds. Combined with FESPACO (Francophone pan-African), Marrakech (Morocco/international), and the Durban FilmMart (industry market), JCC anchors the North African film calendar.","CALENDAR REMINDER:":"Watch jcctunisie.org from mid-2026 for JCC 2026 submission dates.","status":"approved","votes":0}'

echo

# 4. ZIFF (Zanzibar International Film Festival)
insert_opp '{"title":"ZIFF — ZANZIBAR INTERNATIONAL FILM FESTIVAL (Festival of the Dhow Countries)","What Is It?":"The Zanzibar International Film Festival (ZIFF), also known as the Festival of the Dhow Countries, is one of the largest cultural events in East Africa. Founded in 1997, ZIFF celebrates cinema, music, and performing arts from the Dhow Countries — the nations bordering the Indian Ocean including East Africa, the Arabian Peninsula, the Persian Gulf, and South and Southeast Asia. The 29th season ran in 2026. ZIFF screens over 150 films and attracts an audience of 100,000+. The festival is held in the historic Stone Town of Zanzibar, a UNESCO World Heritage Site. ZIFF runs competitive sections for feature films, documentaries, and short films, with awards in multiple categories.","For Films or Series?":"Feature fiction, documentary, short films, animation. Films from the Dhow Countries region and beyond.","What Do You Get If Selected?":"Festival screening and awards eligibility. Access to the ZIFF industry programme. Networking with East African and Indian Ocean region film professionals. Visibility to an audience of 100,000+ in one of Africa'"'"'s most culturally significant settings.","Cost":"Submission via FilmFreeway","Next Deadline":"Annual. Check ziff.or.tz and FilmFreeway for 2026/2027 submission dates.","Apply:":"ziff.or.tz","Who Can Apply / Eligibility":"Filmmakers globally, with focus on the Dhow Countries region (East Africa, Arabian Peninsula, South/Southeast Asia). East African filmmakers especially welcome.","What to Submit":"Completed film via the ZIFF submission platform or FilmFreeway.","Strongest Submission Tips":"ZIFF is the premier film festival for East African filmmakers — complementing Docubox (East African funding) and AFRIFF (West African market). The Dhow Countries focus gives ZIFF a unique cultural perspective that bridges East Africa with the Indian Ocean world. For Kenyan, Tanzanian, Ugandan, and Rwandan filmmakers, ZIFF is a critical visibility platform. The 100,000+ audience makes it one of the most-attended film events on the continent.","CALENDAR REMINDER:":"Check ziff.or.tz for annual submission dates.","status":"approved","votes":0}'

echo

# 5. Gotham Week Project Market
insert_opp '{"title":"GOTHAM WEEK PROJECT MARKET (New York)","What Is It?":"Gotham Week is the annual industry event of The Gotham (formerly IFP), America'"'"'s oldest and most established organisation supporting independent film. The Project Market is a curated marketplace where selected fiction and documentary projects in development or production meet with financiers, sales agents, distributors, and producers over several days of scheduled meetings. Gotham Week takes place annually in September/October in New York City. The Gotham has international partnerships including with Telefilm Canada. Projects are selected through an open application process. The Gotham also runs the Gotham Awards (formerly IFP Spirit Awards), one of the most important independent film award ceremonies.","For Films or Series?":"Feature fiction and documentary. Projects in development or production.","What Do You Get If Selected?":"Scheduled meetings with US and international financiers, sales agents, and distributors. Access to the full Gotham Week industry programme. Visibility in the world'"'"'s largest independent film market. Gotham membership benefits.","Cost":"Application fee. Gotham membership may be required.","Next Deadline":"Annual, September/October. Applications typically open in spring. Check thegotham.org for 2026 dates.","Apply:":"thegotham.org/gotham-week/project-market","Who Can Apply / Eligibility":"Independent filmmakers globally. Projects must be in active development or production. Fiction and documentary.","What to Submit":"Project application including synopsis, director'"'"'s statement, producer'"'"'s statement, budget, and financing plan.","Strongest Submission Tips":"The Gotham Project Market is a strong US entry point for African filmmakers seeking American distribution or financing. New York is home to many documentary funders (including ITVS, already in this guide) and independent distributors. If you have secured initial funding from African or European sources (DFM, Berlinale WCF, HBF), the Gotham Project Market can help you connect with US completion financing and distribution.","CALENDAR REMINDER:":"Watch thegotham.org from spring 2026 for Project Market application dates.","status":"approved","votes":0}'

echo

# 6. KOSINIMA Short Film Grant
insert_opp '{"title":"KOSINIMA SHORT FILM GRANT","What Is It?":"KOSINIMA, Inc. is a 501(c)(3) nonprofit founded by Oluwaseun Babalola that provides films, grants, and career support for filmmakers in Africa and the African diaspora. The KOSINIMA Short Film Grant funds Black woman-identifying or non-binary filmmakers from Africa and the African diaspora (including Europe, the United States, the Caribbean, and South America) to produce short narrative or documentary films. The grant provides $2,500 USD per filmmaker for up to 4 filmmakers per cycle. Past grantees have produced work screened at international festivals. The grant operates on a periodic cycle — submissions open and close throughout the year.","For Films or Series?":"Short films only — narrative or documentary. Up to 4 filmmakers funded per cycle.","What Do You Get If Selected?":"$2,500 USD grant for short film production. Career support and mentorship from KOSINIMA network. Visibility through KOSINIMA'"'"'s platform and festival connections.","Cost":"FREE — No application fee","Next Deadline":"Submissions currently closed. Check kosinima.org/shortfilmgrant for the next open cycle.","Apply:":"kosinima.org/shortfilmgrant","Who Can Apply / Eligibility":"Black woman-identifying or non-binary filmmakers from Africa and the African diaspora (including Europe, United States, Caribbean, South America). Short narrative or documentary film projects.","What to Submit":"Project application as specified on the KOSINIMA website when submissions open.","Strongest Submission Tips":"KOSINIMA fills a critical niche — funding specifically for Black femme filmmakers from Africa and the diaspora. The $2,500 amount is modest but can fully fund a short film in many African contexts. A completed KOSINIMA-funded short can serve as a calling card for larger grants from Docubox, Africa No Filter, or the NFVF first-time filmmaker tier. Check back regularly as submission cycles open periodically.","CALENDAR REMINDER:":"Monitor kosinima.org/shortfilmgrant for next open submission cycle.","status":"approved","votes":0}'

echo

# 7. UNESCO/Tamayouz Cinema Foundation Residency
insert_opp '{"title":"UNESCO / TAMAYOUZ CINEMA FOUNDATION RESIDENCY (Morocco)","What Is It?":"The UNESCO/Tamayouz Cinema Foundation Residency is a fully supported creative residency for young African women filmmakers, held in Morocco. The programme provides mentorship, workshops, and a creative environment for participants to develop their film projects. It is part of UNESCO'"'"'s broader mandate to support cultural diversity and the creative industries in Africa. The residency is run in partnership with the Tamayouz Cinema Foundation, which focuses on empowering women in the African film industry. The programme covers accommodation, meals, and programme costs for selected participants.","For Films or Series?":"Film projects in development — fiction and documentary. Focus on emerging women filmmakers.","What Do You Get If Selected?":"Fully supported residency in Morocco. Mentorship from established filmmakers. Workshops on craft, production, and industry navigation. Time and space to develop your film project. Networking with fellow African women filmmakers.","Cost":"FREE — Fully supported (accommodation, meals, programme costs covered)","Next Deadline":"Periodic. Check UNESCO creativity portal and Tamayouz Cinema Foundation for upcoming calls.","Apply:":"unesco.org/creativity/en","Who Can Apply / Eligibility":"Young African women filmmakers. Emerging talent prioritised. Must have a film project in development.","What to Submit":"Application including project synopsis, director'"'"'s statement, CV, and work sample. Details published when call opens.","Strongest Submission Tips":"This residency is one of the few programmes specifically designed for young African women filmmakers. The Morocco location provides a creative environment at the crossroads of African, Arab, and European film cultures. Use the residency to develop your project to a stage where it is ready for submission to larger development labs (Realness, Locarno Open Doors, Sundance Labs) or funding (AFAC, DFI, HBF). The UNESCO association adds institutional credibility to your CV.","CALENDAR REMINDER:":"Monitor UNESCO creativity portal for upcoming residency calls.","status":"approved","votes":0}'

echo

# 8. Black Film Project (Harvard Hutchins Center)
insert_opp '{"title":"BLACK FILM PROJECT (Harvard Hutchins Center)","What Is It?":"The Black Film Project is a fellowship programme at the Hutchins Center for African & African American Research at Harvard University. The fellowship supports filmmakers exploring the Black experience globally through cinema. Selected fellows receive time, resources, and intellectual community at one of the world'"'"'s leading universities to develop their film projects and engage with scholars, artists, and other fellows. The programme reflects Harvard'"'"'s growing investment in film as a form of scholarship and cultural expression. The 2026 application cycle closed on February 26, 2026 — the next cycle is expected in early 2027.","For Films or Series?":"Film projects exploring the Black experience globally. Fiction and documentary.","What Do You Get If Selected?":"Fellowship at Harvard University'"'"'s Hutchins Center. Access to Harvard'"'"'s intellectual community, libraries, and resources. Time and support to develop your film project. Prestigious institutional association.","Cost":"FREE — Fellowship programme","Next Deadline":"2026 cycle CLOSED (deadline was February 26, 2026). 2027 applications expected early 2027.","Apply:":"hutchinscenter.fas.harvard.edu/black-film-project","Who Can Apply / Eligibility":"Filmmakers globally whose work explores the Black experience. African filmmakers are eligible and encouraged.","What to Submit":"Application including project proposal, CV, work sample, and statement of purpose. Details published when call opens.","Strongest Submission Tips":"The Harvard association makes this one of the most prestigious fellowships available to African filmmakers. The intellectual environment is unique — you will be developing your film project alongside scholars of African and African American studies. This is particularly valuable for filmmakers working on historically or politically significant stories. A Harvard Hutchins fellowship on your CV signals intellectual depth to every funder and festival in this guide. Watch for the 2027 cycle in early 2027.","CALENDAR REMINDER:":"Set a reminder for January 2027 to watch for 2027 Black Film Project applications.","status":"approved","votes":0}'

echo
echo "=== All 8 new listings processed ==="
