#!/bin/bash
export SUPABASE_URL="https://rcgynwcttgvqcnbyfhiz.supabase.co"
export SUPABASE_KEY="sb_publishable_DGjAbWbzmEo7yqEOibia0A_r9mWOu-W"

insert_opp() {
  local json="$1"
  local title=$(echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])" 2>/dev/null)
  local http_code=$(curl -s -o /tmp/sb_resp.json -w "%{http_code}" \
    "${SUPABASE_URL}/rest/v1/opportunities" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=minimal" \
    -d "$json")
  if [ "$http_code" = "201" ]; then
    echo "✓ $title"
  else
    echo "✗ $title (HTTP $http_code)"
    cat /tmp/sb_resp.json
    echo
  fi
}

echo "Inserting 13 remaining opportunities..."
echo

insert_opp '{"title":"AFAC DOCUMENTARY FILM PROGRAM (Arab Fund for Arts & Culture)","What Is It?":"The Arab Fund for Arts and Culture (AFAC) is an independent organisation founded in 2007 to support artists and cultural institutions across the Arab world. Its Documentary Film Program provides financial support to creative documentary filmmakers from the Arab region and diaspora, funding projects across development, production, and post-production stages. AFAC prioritises storytelling-driven, artistically ambitious documentaries. Donors include the Ford Foundation, Open Society Foundations, Magnum Foundation, and Andrew Mellon Foundation. Roughly 42% of grantees are emerging artists and 30% are women.","For Films or Series?":"Creative documentary only. Projects at development, production, or post-production stage.","What Do You Get If Selected?":"Production grant covering project-related expenses including materials, equipment rentals, and fees for artistic and technical collaboration. Director and producer fee of up to 30% of grant amount is allowable.","Cost":"FREE — No application fee","Next Deadline":"DEADLINE: 2 April 2026 at 5:00 PM Beirut time (GMT+3). Online application only.","Apply:":"arabculturefund.org/Programs/7","Who Can Apply / Eligibility":"Filmmakers of Arab origin or nationality — including North African countries: Morocco, Tunisia, Algeria, Libya, Egypt, Sudan, and Mauritania. A non-Arab producer may apply if the director is Arab. No age or experience restrictions.","What to Submit":"Online application form with supporting materials. Submit 24 hours before deadline — AFAC cannot assist with technical issues on deadline day.","Strongest Submission Tips":"AFAC is one of the most important funding bodies for North African filmmakers. These countries are often underserved by sub-Saharan African film initiatives and by European funds. AFAC fills this gap with significant funding and a network connecting North African filmmakers to global distribution.","CALENDAR REMINDER:":"URGENT: Apply before 2 April 2026. Second AFAC call (for fiction cinema) opens later in 2026.","status":"approved","votes":0}'

insert_opp '{"title":"NFVF PRODUCTION & DEVELOPMENT FUNDING (National Film and Video Foundation, South Africa)","What Is It?":"The National Film and Video Foundation is a South African government agency mandated by the Department of Sport, Arts and Culture to support the development, production, marketing, and distribution of South African films. It is the primary public funding body for the South African film industry. The NFVF operates multiple funding tiers: Development Funding for script development; Production Funding for features, documentaries, shorts, and animation including a dedicated tier for first-time filmmakers; Training Provider Grants; and Marketing and Distribution support for international festivals and markets.","For Films or Series?":"Feature fiction, documentary, short films, animation. South African content only.","What Do You Get If Selected?":"Funding varies by tier and project. Multiple call cycles per year. First-time filmmaker short film tier available. International delegation support for festivals and markets.","Cost":"FREE — No application fee","Next Deadline":"Multiple call cycles per year. Check the NFVF website for current open calls.","Apply:":"nfvf.co.za/production-funding","Who Can Apply / Eligibility":"South African production companies with relevant experience and a credible track record. First-time filmmakers are eligible for the short film tier.","What to Submit":"Application form and project documentation as specified per funding tier.","Strongest Submission Tips":"The NFVF is THE primary South African government film fund. If you are based in South Africa, this should be your first port of call. The first-time filmmaker short film tier is a particularly valuable entry point for emerging talent.","CALENDAR REMINDER:":"Check nfvf.co.za regularly for new funding call openings throughout the year.","status":"approved","votes":0}'

insert_opp '{"title":"DOHA FILM INSTITUTE (DFI) GRANTS PROGRAMME","What Is It?":"The Doha Film Institute is the primary engine for independent cinema funding in the MENA region, and one of the most important international grant bodies for filmmakers from the Global South. Founded in Qatar, DFI provides non-recoupable funding of up to $100,000 for feature production through its bi-annual grants programme, which has supported over 1,000 projects from 46 countries. DFI grantees gain access to Qumra, the annual industry event connecting funded filmmakers to international sales agents, producers, and festival programmers.","For Films or Series?":"Feature fiction, documentary, short film, animation.","What Do You Get If Selected?":"Up to $100,000 for feature production. Non-recoupable funding. Access to Qumra. The DFI stamp of approval is widely recognised as a signal of quality.","Cost":"FREE — No application fee","Next Deadline":"Spring 2026 cycle: CLOSED (8 January 2026). Fall 2026 cycle: Expected July-August 2026.","Apply:":"dohafilm.com/en/funding-industry/funding/grants","Who Can Apply / Eligibility":"MENA filmmakers (including North Africa): eligible for all stages. International filmmakers: generally first or second-time directors, primarily post-production funding. Feature budgets must not exceed $2.2 million.","What to Submit":"Online application during open cycles. Full project documentation required.","Strongest Submission Tips":"For North African filmmakers, DFI is one of the most accessible and substantial funding sources with full eligibility across all stages. The 1,000+ project milestone makes a DFI grant a powerful credibility signal for further fundraising.","CALENDAR REMINDER:":"Set a reminder for July 2026 to watch for the Fall 2026 grants cycle opening.","status":"approved","votes":0}'

insert_opp '{"title":"SUNDANCE DOCUMENTARY FUND","What Is It?":"The Sundance Institute Documentary Film Program, established in 2002 with founding support from the Open Society Foundations, supports nonfiction filmmakers worldwide in the production of cinematic documentaries on contemporary themes. Grants of $15,000 to $50,000 for documentary projects at development, production, and post-production stages. This is separate from the Sundance Screenwriters Lab and Episodic Lab. In September 2025, 32 grantees were announced. At Sundance 2026, African filmmakers Olive Nwosu (Nigeria), Bea Wangondu (Kenya), and Praise Odigie Paige (Nigeria) participated prominently.","For Films or Series?":"Documentary only — features and shorts. Any stage.","What Do You Get If Selected?":"$15,000-$50,000 grant. Sundance Institute support and network access. Association with the worlds most prestigious independent film brand.","Cost":"FREE — No application fee","Next Deadline":"2026 cycle expected to open mid-2026. Check sundance.org for announcements.","Apply:":"sundance.org/programs/documentary-film","Who Can Apply / Eligibility":"Global — no geographic restrictions. Strong artistic vision and social relevance are prioritised.","What to Submit":"Project application with treatment, directors statement, work sample, and budget.","Strongest Submission Tips":"The Sundance name carries unmatched prestige. African documentary filmmakers have an increasingly strong track record. A Sundance Documentary Fund grant signals quality to every other funder in this guide. Pair with a DFM pitch or IDFA Forum Pitch for maximum impact.","CALENDAR REMINDER:":"Set a reminder for mid-2026 to watch for the Sundance Documentary Fund call opening.","status":"approved","votes":0}'

insert_opp '{"title":"ITVS OPEN CALL (Independent Television Service / PBS)","What Is It?":"The Independent Television Service (ITVS) funds and presents independent documentaries on PBS — Americas public broadcasting network reaching 120 million viewers. Its Open Call offers up to $400,000 in co-production funding for independent documentary films, from shorts to features, on any subject and in any style. This is the single largest documentary production fund in this guide. ITVS funding comes with PBS broadcast rights in the US.","For Films or Series?":"Documentary only (shorts to features). Any subject, any style. Must be in active production.","What Do You Get If Selected?":"Up to $400,000 co-production funding. PBS broadcast in the United States. ITVS production and distribution support.","Cost":"FREE — No application fee","Next Deadline":"Rolling applications — open year-round. Allow 2-4 weeks for preparation.","Apply:":"itvs.org/funds/open-call","Who Can Apply / Eligibility":"Independent producers globally. Projects must be in active production (not pre-production).","What to Submit":"Project application including rough cut or work sample, budget, distribution plan.","Strongest Submission Tips":"At up to $400,000, this is the largest single documentary fund in this guide. The PBS broadcast pipeline gives African documentaries access to the US market. African filmmakers with partial funding from Hot Docs-Blue Ice, IDFA Bertha Fund, or Berlinale WCF can use ITVS to close their gap at scale. Rolling applications means no deadline pressure.","CALENDAR REMINDER:":"No deadline — apply whenever your project is in active production.","status":"approved","votes":0}'

insert_opp '{"title":"FESPACO (Pan-African Film and Television Festival of Ouagadougou)","What Is It?":"FESPACO is Africas oldest and largest film festival, founded in 1969 in Ouagadougou, Burkina Faso. It is the continents most important celebration of African cinema, operating on a biennial cycle (odd years). The festival accepts for competition only films by African filmmakers — the only major international-class festival with an exclusively African competition. The Golden Stallion of Yennenga is Africas most prestigious film award. The 29th edition (2025) attracted over 100,000 audience. The 30th edition is confirmed for February/March 2027. Call for submissions opened 7 February 2026.","For Films or Series?":"All formats — feature fiction, documentary, series, animation, short film. Competition restricted to African filmmakers.","What Do You Get If Selected?":"Screening at Africas most prestigious film festival. Eligibility for the Golden Stallion of Yennenga. Networking with pan-African and international industry professionals.","Cost":"FREE submission","Next Deadline":"Call for films for 30th edition (2027) opened February 2026. Check fespaco.bf for deadline.","Apply:":"fespaco.bf","Who Can Apply / Eligibility":"African filmmakers only. Films must be directed by filmmakers of African nationality or origin.","What to Submit":"Completed film for festival selection. Details on the official FESPACO website.","Strongest Submission Tips":"FESPACO is foundational to the African film ecosystem. Having your film selected — or winning the Golden Stallion — establishes your reputation across the continent. Francophone African filmmakers should treat FESPACO as a cornerstone of their festival strategy. The 2027 call is already open.","CALENDAR REMINDER:":"2027 call for films is OPEN NOW. Check fespaco.bf for submission deadline.","status":"approved","votes":0}'

insert_opp '{"title":"DOCUBOX — EAST AFRICAN DOCUMENTARY FILM FUND","What Is It?":"Docubox is the only dedicated film fund for East African documentary filmmakers. Founded in 2013 by Kenyan filmmaker Judy Kibinge, it provides development and production grants of $5,000-$20,000 to documentary, short fiction, and experimental filmmakers in Kenya, Uganda, Tanzania, and Rwanda. Beyond funding, Docubox runs workshops, labs, and mentorship programmes. Supported by the Hewlett Foundation and Climate Justice Resilience Fund. Alumni include The Letter, an acclaimed Kenyan documentary. Expanding to Morocco in 2025-2026.","For Films or Series?":"Documentary, short fiction, experimental. East Africa only (Kenya, Uganda, Tanzania, Rwanda).","What Do You Get If Selected?":"$5,000-$20,000 grant. Workshops, labs, and mentorship. Community of East African documentary filmmakers.","Cost":"FREE — No application fee","Next Deadline":"Annual cycle. Check mydocubox.org for current call status.","Apply:":"mydocubox.org/funding","Who Can Apply / Eligibility":"Filmmakers based in Kenya, Uganda, Tanzania, or Rwanda.","What to Submit":"Project application as specified on the Docubox website.","Strongest Submission Tips":"East Africa has a rapidly growing film sector but has historically been underserved by international film funds. Docubox fills this gap with funding, training, and community. For East African filmmakers, this is the most directly relevant opportunity in this guide.","CALENDAR REMINDER:":"Check mydocubox.org for annual call opening dates.","status":"approved","votes":0}'

insert_opp '{"title":"AFRIFF (Africa International Film Festival, Lagos)","What Is It?":"AFRIFF is Africas premier film festival based in Nigeria, held annually in November in Lagos. Founded in 2010 by Chioma Ude, it has grown into one of the continents most important platforms for African cinema, connecting Nollywood and West African film to international markets. AFRIFF runs a full industry programme including content licensing, co-production deals, and distribution agreements. Partnership with MTN — Africas largest telco. The NFVF sponsors a South African delegation annually.","For Films or Series?":"Features, documentaries, shorts, animation, student films.","What Do You Get If Selected?":"Festival screening and awards eligibility. Access to industry programme including licensing, co-production, and distribution. Networking with pan-African and international professionals.","Cost":"Submission fee via FilmFreeway","Next Deadline":"Annual. Submissions typically open mid-year for November festival. Check afriff.com.","Apply:":"afriff.com","Who Can Apply / Eligibility":"Open to filmmakers globally with focus on African cinema. Submissions via FilmFreeway.","What to Submit":"Completed film via FilmFreeway.","Strongest Submission Tips":"AFRIFF is the primary industry platform for Nigerias film sector — the largest in Africa by volume. Combined with the Durban FilmMart (Southern Africa) and FESPACO (Francophone Africa), AFRIFF completes the trio of continent-defining African film industry events.","CALENDAR REMINDER:":"Watch afriff.com from mid-2026 for submission opening dates.","status":"approved","votes":0}'

insert_opp '{"title":"ACP-EU CULTURE PROGRAMME","What Is It?":"The ACP-EU Culture Programme is funded by the European Union to support cultural and creative industries in African, Caribbean, and Pacific (ACP) countries. It provides grants of up to 200,000 EUR or more for international co-production, film development, and distribution projects involving collaboration between ACP and European production companies. One of the largest structured co-production funding mechanisms available to African filmmakers.","For Films or Series?":"Fiction, documentary, animation, short film, web content. Must be international co-production.","What Do You Get If Selected?":"Up to 200,000 EUR+ depending on project scope. Co-production support, development funding, and distribution assistance.","Cost":"FREE — No application fee","Next Deadline":"Periodic calls for proposals. Check acp-ue-culture.eu for current opportunities.","Apply:":"acp-ue-culture.eu/en","Who Can Apply / Eligibility":"Production companies from ACP countries (all Sub-Saharan Africa plus Caribbean and Pacific) in partnership with EU-based companies. Requires at least two companies — one ACP, one EU.","What to Submit":"Project proposal as specified in the call for proposals.","Strongest Submission Tips":"At up to 200,000 EUR, this is one of the largest funding opportunities available. If you have connected with a European producer at CineMart, Berlinale Co-Pro Series Market, or TorinoFilmLab, the ACP-EU Culture Programme is a natural next step for significant production financing.","CALENDAR REMINDER:":"Monitor acp-ue-culture.eu for periodic calls for proposals.","status":"approved","votes":0}'

insert_opp '{"title":"MULTICHOICE TALENT FACTORY (MTF)","What Is It?":"The MultiChoice Talent Factory is a pan-African film and television training programme operated by the MultiChoice Group (now Canal+). Three regional academies: West Africa (Lagos), East Africa (Nairobi), Southern Africa (Lusaka). Each takes approximately 20 students per cohort for a fully-sponsored 12-month programme covering directing, producing, cinematography, editing, sound design, and more. Students work on real productions. Despite the Showmax shutdown in March 2026, MTF continues as a separate initiative.","For Films or Series?":"Training programme covering all formats — film and television production.","What Do You Get If Selected?":"Fully-sponsored 12-month programme — tuition, accommodation, and living expenses covered. Hands-on production experience. Continental alumni network.","Cost":"FREE — Fully sponsored","Next Deadline":"2026 applications CLOSED (deadline 27 February 2026). 2027 applications expected January-February 2027.","Apply:":"multichoicetalentfactory.com","Who Can Apply / Eligibility":"Aspiring filmmakers and media professionals from across Africa. Must hold at least a tertiary qualification.","What to Submit":"Application form, portfolio of work, and motivation.","Strongest Submission Tips":"The only structured pan-African training programme at this scale — fully funded, 12 months, three regional hubs. For emerging filmmakers without formal industry training, MTF is an unmatched entry point. Graduates gain production credits that strengthen applications to every fund in this guide.","CALENDAR REMINDER:":"Set a reminder for January 2027 to watch for 2027 MTF applications opening.","status":"approved","votes":0}'

insert_opp '{"title":"CPH:FORUM (CPH:DOX Copenhagen Documentary Festival)","What Is It?":"CPH:FORUM is the flagship financing and co-production event of CPH:DOX — the Copenhagen International Documentary Film Festival. Each March, approximately 30 documentary projects are selected for live pitch presentations to international financiers, broadcasters, and distributors. The 2026 edition brought together 101 directors and producers from 23 countries. Alongside IDFA Forum Pitch (Amsterdam, November) and Sheffield DocFest MeetMarket (June), CPH:FORUM completes the trio of the worlds most important documentary financing forums.","For Films or Series?":"Documentary only. Projects from early development to late production.","What Do You Get If Selected?":"Live pitch to international financiers, broadcasters, sales agents. Co-production meetings. Awards and prizes. Access to full CPH:DOX industry programme.","Cost":"Accreditation fee for CPH:DOX industry programme","Next Deadline":"Annual, March. 2026 edition complete. Submissions for 2027 open autumn 2026.","Apply:":"cphdox.dk","Who Can Apply / Eligibility":"Documentary filmmakers globally. Projects selected by CPH:DOX programming team.","What to Submit":"Project submission via CPH:DOX platform when call opens.","Strongest Submission Tips":"Target all three top doc financing forums: CPH:FORUM (March), Sheffield MeetMarket (June), IDFA Forum Pitch (November). Same universe of European broadcasters and sales agents — three chances per year. An IDFA Bertha Fund or Hot Docs-Blue Ice grant strengthens your application.","CALENDAR REMINDER:":"Set a reminder for autumn 2026 to watch for CPH:FORUM 2027 submissions opening.","status":"approved","votes":0}'

insert_opp '{"title":"AFRICA NO FILTER / KEKERE STORYTELLERS FUND","What Is It?":"Africa No Filter is a donor collaborative focused on shifting stereotypical narratives about Africa. Its Kekere Storytellers Fund provides micro-grants to emerging African content creators whose work tells African stories beyond stereotypes of poverty, conflict, disease, poor leadership, and corruption. Supports short films (up to $5,000), feature films (up to $10,000), documentaries, digital storytelling, and youth-led content.","For Films or Series?":"Short films, feature films, documentaries, digital storytelling, youth-led content.","What Do You Get If Selected?":"Micro-grants: up to $5,000 for shorts, up to $10,000 for features. Part of the Africa No Filter narrative change ecosystem.","Cost":"FREE — No application fee","Next Deadline":"Periodic calls. Check africanofilter.org for current opportunities.","Apply:":"africanofilter.org/kekere-storytellers-fund","Who Can Apply / Eligibility":"Filmmakers and content creators based in Africa or members of the African diaspora.","What to Submit":"Project proposal as specified in the call.","Strongest Submission Tips":"This fund fills a critical gap for emerging creators who need smaller amounts to get started. A completed short film funded by Africa No Filter can serve as proof of concept for applications to larger development labs and production funds.","CALENDAR REMINDER:":"Monitor africanofilter.org for periodic call openings.","status":"approved","votes":0}'

insert_opp '{"title":"MERCK FOUNDATION FILM AWARDS 2026","What Is It?":"The Merck Foundation Film Awards More Than a Mother is an annual competition launched in partnership with African First Ladies, inviting African filmmakers, film students, and young creative talents to submit long or short films addressing critical social issues including infertility stigma, girls education, women empowerment, child marriage, and FGM. Cash prizes awarded across categories.","For Films or Series?":"Long or short films — drama, documentary, or docudrama. Must address Merck Foundation focus themes.","What Do You Get If Selected?":"Cash prizes across categories. Visibility through partnership with African First Ladies. Recognition as a social-impact filmmaker.","Cost":"FREE — No application fee","Next Deadline":"OPEN NOW. Deadline: 30 September 2026.","Apply:":"merck-foundation.com/Awards/merck-foundation-film-awards-more-than-a-mother","Who Can Apply / Eligibility":"All African filmmakers, film students, and young creative talents.","What to Submit":"Completed long or short film (drama, documentary, or docudrama) addressing one of the specified social themes.","Strongest Submission Tips":"The long application window (until September 2026) and broad eligibility make this accessible. The social-impact theme aligns with priorities of many international documentary funds — a Merck Foundation award strengthens applications to these larger funds.","CALENDAR REMINDER:":"Deadline 30 September 2026. Plenty of time to submit.","status":"approved","votes":0}'

echo
echo "Done! All insertions complete."
