#!/bin/bash
export SUPABASE_URL="https://rcgynwcttgvqcnbyfhiz.supabase.co"
export SUPABASE_KEY="sb_publishable_DGjAbWbzmEo7yqEOibia0A_r9mWOu-W"

insert_opp() {
  local json="$1"
  local title=$(echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])" 2>/dev/null)
  local http_code=$(curl -s -o /tmp/sb_resp.json -w "%{http_code}" \
    "${SUPABASE_URL}/rest/v1/opportunities" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=minimal" \
    -d "$json")
  if [ "$http_code" = "201" ]; then
    echo "✓ OPP: $title"
  else
    echo "✗ OPP: $title (HTTP $http_code)"
    cat /tmp/sb_resp.json
    echo
  fi
}

insert_news() {
  local json="$1"
  local title=$(echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['title'])" 2>/dev/null)
  local http_code=$(curl -s -o /tmp/sb_resp.json -w "%{http_code}" \
    "${SUPABASE_URL}/rest/v1/news" \
    -H "apikey: ${SUPABASE_KEY}" \
    -H "Authorization: Bearer ${SUPABASE_KEY}" \
    -H "Content-Type: application/json" \
    -H "Prefer: return=minimal" \
    -d "$json")
  if [ "$http_code" = "201" ]; then
    echo "✓ NEWS: $title"
  else
    echo "✗ NEWS: $title (HTTP $http_code)"
    cat /tmp/sb_resp.json
    echo
  fi
}

echo "=== Inserting AI & Emerging Tech Opportunities ==="
echo

insert_opp '{"title":"RUNWAY AI FESTIVAL (AIF 2026)","What Is It?":"Runway'\''s fourth annual AI Festival — originally established in 2022 as the world'\''s first AI Film Festival. AIF has evolved into an interdisciplinary celebration of creatives experimenting at the forefront of art and technology, spanning Film, Design, New Media, Fashion, Advertising, and Gaming. Finalists are showcased both virtually and at gala screenings at Alice Tully Hall (NYC, June 11) and The Broad Stage Theater (LA, June 18). Winning submissions are shown at partner festivals worldwide. In 2025, AIF received over 6,000 submissions — up from 300 in the first edition. Following the 2025 festival, IMAX struck a deal with Runway to show winning films in cinemas across 10 US cities. Malagasy filmmaker Herinarivo Rakotomanana was a 2025 finalist with More Tears Than Harm.","For Films or Series?":"Short films (3-15 minutes) that include the use of generative video. Must be a fully contained, linear narrative.","What Do You Get If Selected?":"Screening at gala events in NYC and LA. IMAX cinema showcase potential. Global exposure through partner festivals. Industry recognition from the leading AI creative platform.","Cost":"FREE — No entry fee","Next Deadline":"CLOSING NOW: March 31, 2026 at 11:59 PM ET","Apply:":"aif.runwayml.com/submission","Who Can Apply / Eligibility":"Global — no geographic restrictions. Films must include generative video (any AI tool, not just Runway). 3-15 minutes in length.","What to Submit":"Film submission via the AIF portal with description of AI techniques used.","Strongest Submission Tips":"This is THE most prestigious AI film platform globally. An African filmmaker (Herinarivo Rakotomanana, Madagascar) was already a finalist. The IMAX deal makes this a genuine distribution opportunity, not just a festival screening. Use the deadline urgency — March 31 is days away.","CALENDAR REMINDER:":"URGENT: Submit before March 31, 2026. Screenings in NYC (June 11) and LA (June 18).","category":"AI & Emerging Tech","application_status":"closing_soon","status":"approved","votes":0}'

insert_opp '{"title":"RUNWAY HUNDRED FILM FUND","What Is It?":"A $5 million fund by Runway to finance up to 100 films that use AI in their production pipeline. The Hundred Film Fund was created because traditional funding mechanisms often overlook new and emerging visions. Grants support features, shorts, documentaries, experimental projects, music videos and more. The advisory board includes Jane Rosenthal (co-founder of Tribeca Festival, producer of The Irishman), will.i.am, Richard Kerris (VP GM Media & Entertainment at NVIDIA), and Christina Lee Storm (Governor of Television Academy'\''s EMPG). Runway Studios provides additional production support to selected projects.","For Films or Series?":"All formats — features, shorts, documentaries, experimental, music videos. Must utilise Runway tools throughout the production pipeline.","What Do You Get If Selected?":"Grant funding (up to ~$50,000 per project). Runway Studios production support. Access to advisory board network including Tribeca, NVIDIA, and industry leaders.","Cost":"FREE — No application fee","Next Deadline":"Rolling applications — open year-round","Apply:":"runwayml.com/hundred-film-fund/submit","Who Can Apply / Eligibility":"Global. Must be working on a film project that utilises Runway throughout the production pipeline and be in need of additional funding to complete.","What to Submit":"Application via the Runway submission portal with project details and demonstration of Runway tool usage.","Strongest Submission Tips":"At $5M total commitment funding 100 films, this is the largest dedicated AI filmmaking fund in the world. Rolling applications mean no deadline pressure. The Tribeca partnership and NVIDIA advisory board give this institutional credibility that no other AI fund has. African filmmakers with a Runway-based project should apply immediately.","CALENDAR REMINDER:":"No deadline — apply whenever your project is ready. Rolling applications.","category":"AI & Emerging Tech","application_status":"open","status":"approved","votes":0}'

insert_opp '{"title":"NAIJA AI FILM FESTIVAL (NAIFF)","What Is It?":"Africa'\''s first AI film festival, founded by Nigerian filmmaker and producer Obinna Okerekeocha. Held in Lagos at Alliance Française, NAIFF received 490 submissions in its inaugural edition and featured a global showcase of AI-assisted films, panel discussions, local AI tool showcases (Switch Studio, AIstudio.ng), and Gen Jam — a training session where attendees created AI films from scratch in four hours. The festival'\''s Best AI Long-Form Film went to Godzilla in Lagos by Nirvs AI. NAIFF is building a community to reimagine African filmmaking with AI, addressing the gap between Africa'\''s creative talent and global infrastructure. The festival emerged just months after Makemation — Nigeria'\''s first AI-assisted feature film — grossed ₦32 million at the box office in 4 days.","For Films or Series?":"AI-assisted films — all formats including short films, features, and experimental.","What Do You Get If Selected?":"Festival screening and awards. Community access to Africa'\''s AI filmmaking network. Training and mentorship. Local AI tool showcases.","Cost":"Via FilmFreeway — check listing for current fees","Next Deadline":"2nd edition expected 2026. Check naijaaifilmfest.com for announcements.","Apply:":"naijaaifilmfest.com","Who Can Apply / Eligibility":"Global submissions welcome, with a focus on African and African-diaspora creators. Films must incorporate AI tools in the creative process.","What to Submit":"Completed AI-assisted film via FilmFreeway or the NAIFF website.","Strongest Submission Tips":"This is ground zero for AI filmmaking in Africa. If you are an African creator exploring AI tools, NAIFF is your home festival. The community network is as valuable as the screening — connecting you to other AI-forward African filmmakers, local tool developers, and the growing Lagos AI creative scene.","CALENDAR REMINDER:":"Watch naijaaifilmfest.com for 2nd edition call for submissions in 2026.","category":"AI & Emerging Tech","application_status":"upcoming","status":"approved","votes":0}'

insert_opp '{"title":"1 BILLION FOLLOWERS SUMMIT — AI FILM AWARD (Dubai)","What Is It?":"The world'\''s largest AI film prize — $1 million — launched in collaboration with Google'\''s Gemini at the 1 Billion Followers Summit in Dubai. The inaugural award in 2025 was won by Tunisian filmmaker Zoubeir Jlassi for his short film Lily, created entirely with Google Gemini tools. The award was presented by Sheikha Latifa bint Mohammed bin Rashid Al Maktoum, chairperson of the Dubai Culture and Arts Authority. This prize proves that African and Arab creators can compete at the absolute highest level in AI filmmaking — and win.","For Films or Series?":"AI-generated or AI-assisted short films.","What Do You Get If Selected?":"Grand prize: $1,000,000. Global media exposure. Screening at the 1 Billion Followers Summit in Dubai. Association with Google Gemini.","Cost":"Check submission terms for current edition","Next Deadline":"Annual. Next edition expected late 2026. Monitor 1billionfollowers.ae.","Apply:":"1billionfollowers.ae","Who Can Apply / Eligibility":"Global. Films should demonstrate significant use of AI tools in the creative process.","What to Submit":"AI-generated or AI-assisted short film as specified in the call.","Strongest Submission Tips":"A Tunisian filmmaker won the inaugural $1M prize. This is proof of concept that African creators can win the biggest AI film prizes in the world. The Google Gemini partnership means the tools are accessible — Gemini is free to use. Start experimenting now and submit to the next edition.","CALENDAR REMINDER:":"Monitor 1billionfollowers.ae for the next edition announcement (expected late 2026).","category":"AI & Emerging Tech","application_status":"upcoming","status":"approved","votes":0}'

insert_opp '{"title":"AI FOR GOOD FILM FESTIVAL (ITU / United Nations)","What Is It?":"The AI for Good Film Festival is an initiative by the International Telecommunication Union (ITU), a UN agency, inviting creatives to explore the potential of AI in scriptwriting, storyboarding, image creation, digital effects, and more. The festival is part of the broader AI for Good platform, which connects AI innovators with problem solvers to advance the UN Sustainable Development Goals. Finalists are invited to participate in the AI for Good Global Summit with an exclusive Speaker Pass — providing unparalleled networking with global policymakers, technologists, and industry leaders.","For Films or Series?":"AI-generated or AI-enhanced films. Original works that transport audiences to new worlds, narratives, and possibilities.","What Do You Get If Selected?":"Screening at AI for Good events. Exclusive Speaker Pass to the AI for Good Global Summit 2026. Global UN platform exposure. Networking with international policymakers and tech leaders.","Cost":"FREE — No application fee","Next Deadline":"2026 cycle — check aiforgood.itu.int for current submission dates.","Apply:":"aiforgood.itu.int/ai-for-good-film-festival","Who Can Apply / Eligibility":"Global. Filmmakers must uphold IP rights and maintain transparency in AI applications. Must secure all necessary permissions for copyrighted material.","What to Submit":"Original AI-generated or AI-enhanced film with documentation of AI usage.","Strongest Submission Tips":"The UN backing gives this festival unique credibility and a completely different audience from Runway AIF or NAIFF. The Speaker Pass to the Global Summit is exceptionally valuable for networking beyond the film industry — connecting to tech funders, policy makers, and development organisations. African filmmakers working on social-impact themes should prioritise this.","CALENDAR REMINDER:":"Check aiforgood.itu.int for 2026 submission dates.","category":"AI & Emerging Tech","application_status":"upcoming","status":"approved","votes":0}'

insert_opp '{"title":"METAMORPH AI AWARD 2026","What Is It?":"The MetaMorph AI Award is a UK-based global AI film and music festival, judged by a heavyweight panel including John Rhys-Davies (Lord of the Rings, Indiana Jones), David Nutter (Game of Thrones, The Flash), and Timbaland'\''s Stage Zero team — the AI-powered entertainment company founded by Timbaland, Rocky Mudaliar, and Zayd Portillo. Categories span AI Film, AI Animation, and AI Music. The music crossover through Stage Zero opens a unique creative avenue — AI filmmakers working with AI-generated or AI-enhanced soundtracks.","For Films or Series?":"AI films, AI animation, AI music. Multiple categories.","What Do You Get If Selected?":"Awards judged by industry heavyweights. Exposure through Stage Zero (Timbaland'\''s AI entertainment company). Cross-discipline recognition across film and music.","Cost":"Check metamorph-award.com for current submission fees","Next Deadline":"2026 submissions open. Check metamorph-award.com for deadlines.","Apply:":"metamorph-award.com","Who Can Apply / Eligibility":"Global — no geographic restrictions.","What to Submit":"AI film, animation, or music submission as specified per category.","Strongest Submission Tips":"The Timbaland/Stage Zero connection is unique — this is the only AI festival bridging film and music. If your project has a strong soundtrack or musical element enhanced by AI, MetaMorph is your target. The high-profile jury (Rhys-Davies, Nutter) ensures industry attention.","CALENDAR REMINDER:":"Check metamorph-award.com for 2026 deadlines.","category":"AI & Emerging Tech","application_status":"open","status":"approved","votes":0}'

insert_opp '{"title":"AI FILM AWARDS — CANNES 2026 (3rd Edition)","What Is It?":"The AI Film Awards (AI Film & Ads Awards) is an international festival held during the Cannes Film Festival, organised by KM Universe. Now in its third edition, it celebrates how AI is transforming storytelling, imagery, and modern production techniques. The Cannes timing provides unmatched visibility — your AI film screens in the same city, same week, as the world'\''s most prestigious film festival. Categories include AI narrative films, AI commercials/ads, and experimental AI works.","For Films or Series?":"AI films and AI-enhanced advertisements/commercials. Multiple categories.","What Do You Get If Selected?":"Screening during Cannes Film Festival week. Awards across multiple categories. Industry visibility at the world'\''s top film market.","Cost":"Submissions via FilmFreeway — check for current fees. Free submission available with membership.","Next Deadline":"2026 submissions via FilmFreeway. Check listing for current deadline.","Apply:":"filmfreeway.com/aifilmawards2025","Who Can Apply / Eligibility":"Global. AI must be a significant component of the filmmaking process.","What to Submit":"Film submission via FilmFreeway.","Strongest Submission Tips":"The Cannes timing is the key differentiator. While this is not part of the official Cannes selection, screening your AI work in Cannes during festival week puts you in front of every buyer, sales agent, and programmer on earth. Pair with an application to the Marché du Film for maximum impact.","CALENDAR REMINDER:":"Check FilmFreeway listing for 2026 submission deadline (typically early 2026 for May festival).","category":"AI & Emerging Tech","application_status":"open","status":"approved","votes":0}'

echo
echo "=== Inserting AI News Items ==="
echo

insert_news '{"title":"Makemation: Nigeria'\''s First AI Feature Film Grosses ₦32M in 4 Days","summary":"Nigeria'\''s first AI-assisted feature film, starring Richard Mofe-Damijo, Shaffy Bello, and Jide Kosoko, climbed to third place at the box office nationwide — proof that AI-enhanced African cinema has commercial appeal.","content":"Makemation premiered in Nigerian cinemas in April 2025 and grossed ₦32 million in just four days, climbing to third place nationwide behind Ryan Coogler'\''s Sinners and Ori: The Rebirth. The film'\''s success demonstrates that audiences are ready for AI-assisted African cinema. For filmmakers, this is a signal: the tools are here, the audience is willing, and the market is real.","category":"industry_news","url":"https://nairametrics.com/2025/04/22/africas-no-1-ai-film-makemation-grosses-n32-9-million-in-4-days-at-nigerian-cinemas/"}'

insert_news '{"title":"Tunisian Filmmaker Wins $1 Million AI Film Award in Dubai","summary":"Zoubeir Jlassi'\''s short film Lily, created entirely with Google Gemini, won the world'\''s largest AI film prize at the 1 Billion Followers Summit — a milestone for African and Arab creators.","content":"Tunisian filmmaker Zoubeir Jlassi won the inaugural $1 million AI Film Award at the 1 Billion Followers Summit in Dubai for his short film Lily, created entirely with Google Gemini tools. The award was presented by Sheikha Latifa bint Mohammed bin Rashid Al Maktoum. This is definitive proof that African creators can compete and win at the highest level of AI filmmaking.","category":"new_opportunity","url":"https://www.arabnews.com/node/2628957/lifestyle"}'

insert_news '{"title":"Oscars Rule AI Films Eligible — Same Treatment as Traditional Films","summary":"The Academy of Motion Picture Arts and Sciences has officially clarified that films using AI tools will be treated the same as traditional films for Oscar eligibility.","content":"In a landmark ruling, the Oscars have officially clarified that AI-made films will be treated the same as traditional films for eligibility purposes. This signals global institutional acceptance of AI as a legitimate part of the filmmaking process. For African filmmakers exploring AI tools, this removes the last stigma barrier — your AI-enhanced film is now eligible for the same recognition as any other.","category":"industry_news","url":"https://www.bbc.com/news/articles/cqx4y1lrz2vo"}'

insert_news '{"title":"Africa'\''s AI Film Ground Zero: NAIFF Launches in Lagos","summary":"The Naija AI Film Festival — Africa'\''s first AI film festival — received 490 submissions and featured a global showcase at Alliance Française Lagos, signalling a new chapter for the continent'\''s creative economy.","content":"Hundreds of filmmakers and technologists gathered at Alliance Française in Lagos for Africa'\''s first AI film festival. The Naija AI Film Festival (NAIFF) received 490 submissions from around the world. Godzilla in Lagos by Nirvs AI won Best AI Long-Form Film. The festival included Gen Jam — a hands-on session where attendees created AI films from scratch in four hours. NAIFF is building a community to reimagine African filmmaking with AI.","category":"new_opportunity","url":"https://www.readcommunique.com/p/ai-filmmaking-in-africa"}'

echo
echo "=== All AI data inserted ==="
