-- Seed: Directory listings for South Africa & Nigeria
-- ~80 real industry listings across companies, services, agencies, training
-- Run in Supabase SQL Editor
-- All inserted as status='approved' so they appear immediately

-- ============================================================
-- SOUTH AFRICA — Production Companies
-- ============================================================
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, speciality, notable_projects, year_founded, company_size, status) VALUES
('Triggerfish Animation Studios', 'company', 'Animation', 'Africa''s leading animation studio. Produced Netflix and Disney projects. Pioneered remote collaboration across the continent.', 'South Africa', 'Cape Town', 'https://www.triggerfishstudios.com', 'Animation, Feature Film, Series', 'Seal Team, Khumba, Mama K''s Team 4 (Netflix)', 1996, 'major', 'approved'),
('Film Afrika Worldwide', 'company', 'Line Production', 'One of Africa''s largest service production companies. Full-service line production for international features, commercials, and series.', 'South Africa', 'Johannesburg', 'https://www.filmafrika.com', 'Line Production, Service Production, Commercial', 'Avengers: Age of Ultron, The Woman King, Blood Diamond', 1990, 'major', 'approved'),
('Videovision Entertainment', 'company', 'Fiction', 'Leading South African production company behind award-winning local and international features and television.', 'South Africa', 'Durban', 'https://www.videovision.co.za', 'Feature Film, Television, Documentary', 'Tsotsi (Academy Award), Yesterday, Zulu Love Letter', 1990, 'major', 'approved'),
('Moonlighting Films', 'company', 'Commercial', 'Premier commercial production company. Award-winning work across advertising, branded content, and music videos.', 'South Africa', 'Cape Town', 'https://www.moonlighting.co.za', 'Commercial, Branded Content, Music Video', 'Multiple Cannes Lions, Loeries Grand Prix campaigns', 1997, 'major', 'approved'),
('Urucu Media', 'company', 'Fiction', 'Independent production company focused on authentic African stories for local and international audiences.', 'South Africa', 'Cape Town', 'https://www.urucumedia.com', 'Feature Film, Series, Documentary', 'Five Fingers for Marseilles, This Is Not a Burial It''s a Resurrection', 2012, 'mid', 'approved'),
('Gambit Films', 'company', 'Fiction', 'Award-winning production company creating bold South African cinema. Known for socially relevant narratives.', 'South Africa', 'Johannesburg', 'https://www.gambitfilms.com', 'Feature Film, Documentary, Series', 'Of Good Report, Inxeba (The Wound)', 2009, 'mid', 'approved'),
('Chocolate Tribe', 'company', 'VFX & CGI', 'Visual effects and animation studio delivering world-class VFX for local and international productions.', 'South Africa', 'Cape Town', 'https://www.chocolatetribe.com', 'VFX, CGI, Animation, Motion Graphics', 'Blood & Water (Netflix), Raised by Wolves', 2005, 'mid', 'approved'),
('Waterfront Studios', 'company', 'Studio / Facility', 'State-of-the-art film studio complex at the V&A Waterfront. Multiple stages, workshops, and production offices.', 'South Africa', 'Cape Town', 'https://www.waterfrontstudios.co.za', 'Studio Facility, Sound Stages, Production Offices', 'Multiple international features and series', 2010, 'major', 'approved'),
('Cape Town Film Studios', 'company', 'Studio / Facility', 'Africa''s first custom-built Hollywood-style film studio. 4 sound stages, backlot, workshops, and full production infrastructure.', 'South Africa', 'Cape Town', 'https://www.capetownfilmstudios.co.za', 'Sound Stages, Backlot, Production Facilities', 'Maze Runner, Black Sails, Blood Drive', 2010, 'major', 'approved'),
('Known Associates Entertainment', 'company', 'Fiction', 'Dynamic production company creating premium local content for South African and international broadcasters.', 'South Africa', 'Johannesburg', 'https://www.knownassociates.co.za', 'Television Series, Feature Film', 'Reyka (M-Net/Fremantle), Blood Psalms', 2015, 'mid', 'approved'),
('Cinga Films', 'company', 'Co-Production', 'Boutique co-production company specialising in South-South and European co-productions with African talent.', 'South Africa', 'Cape Town', NULL, 'Co-Production, Feature Film, Documentary', 'Multiple Africa-Europe co-productions', 2014, 'indie', 'approved');

-- SOUTH AFRICA — Services (Gear Houses, Studios, Post)
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, service_type, pricing_tier, status) VALUES
('Media Film Service', 'service', 'Gear House', 'One of South Africa''s largest camera and lighting rental houses. ARRI, RED, Sony, and full grip packages.', 'South Africa', 'Cape Town', 'https://www.mediafilmservice.com', 'Camera Rental, Lighting, Grip', 'premium', 'approved'),
('Panalux South Africa', 'service', 'Gear House', 'International lighting rental company with full South African operations. LED, HMI, tungsten, and rigging.', 'South Africa', 'Cape Town', 'https://www.panalux.com', 'Lighting Rental, Rigging', 'premium', 'approved'),
('Panavision Cape Town', 'service', 'Gear House', 'World-renowned camera rental house with Cape Town facility. Full Panavision and ARRI camera systems.', 'South Africa', 'Cape Town', 'https://www.panavision.com', 'Camera Rental, Lenses, Accessories', 'premium', 'approved'),
('Digital Film', 'service', 'Gear House', 'Full-service camera, lighting, and grip rental. Specialises in RED, ARRI, and Sony camera systems for features and commercials.', 'South Africa', 'Cape Town', 'https://www.digitalfilm.co.za', 'Camera Rental, Lighting, Grip', 'mid', 'approved'),
('Blade Films', 'service', 'Aerial & Drone', 'Aerial cinematography specialists. Licensed drone and helicopter filming for features, commercials, and documentaries.', 'South Africa', 'Cape Town', 'https://www.bladefilms.co.za', 'Aerial Cinematography, Drone, Helicopter', 'premium', 'approved'),
('Refinery Post Production', 'service', 'Post-Production', 'Full post-production facility: offline/online editing, color grading, VFX, and sound design for film and TV.', 'South Africa', 'Johannesburg', 'https://www.refinerypost.co.za', 'Editing, Color Grading, VFX, Sound', 'premium', 'approved'),
('Bling Entertainment', 'service', 'Post-Production', 'Creative post-production studio offering editing, color, VFX compositing, and finishing for features and commercials.', 'South Africa', 'Cape Town', NULL, 'Editing, Color Grading, VFX', 'mid', 'approved'),
('Studio 52', 'service', 'Sound Studio', 'Dolby-certified sound mixing and recording studio. ADR, Foley, sound design, and 5.1/7.1 mixing for cinema.', 'South Africa', 'Johannesburg', NULL, 'Sound Mixing, ADR, Foley, Sound Design', 'premium', 'approved'),
('The Blowfish Agency', 'service', 'Location Services', 'Full-service location scouting and management across South Africa. Specialises in international productions needing diverse SA locations.', 'South Africa', 'Cape Town', 'https://www.blowfish.co.za', 'Location Scouting, Location Management', 'mid', 'approved'),
('Panda Post', 'service', 'DCP & Deliverables', 'Digital cinema mastering, DCP creation, and deliverables preparation for festival and theatrical distribution.', 'South Africa', 'Cape Town', NULL, 'DCP, Mastering, Deliverables, QC', 'mid', 'approved'),
('Subtitles.co.za', 'service', 'Subtitling & Localization', 'Professional subtitling and closed captioning in all 11 official South African languages plus international languages.', 'South Africa', 'Johannesburg', NULL, 'Subtitling, Closed Captioning, Localization', 'mid', 'approved'),
('Cape Casting', 'service', 'Casting', 'Established casting agency for film, TV, and commercials. Extensive talent database across all demographics.', 'South Africa', 'Cape Town', NULL, 'Casting, Talent Search', 'mid', 'approved');

-- SOUTH AFRICA — Agencies
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, status) VALUES
('Artists International Group (AIG)', 'agency', 'Talent Agency', 'Leading South African talent agency representing actors, presenters, and performers for film, TV, and stage.', 'South Africa', 'Johannesburg', NULL, 'approved'),
('Gaenor Artiste Management', 'agency', 'Talent Agency', 'Boutique talent agency representing top South African actors and performers for local and international work.', 'South Africa', 'Cape Town', NULL, 'approved'),
('MoB Agency', 'agency', 'Crew Agency', 'Creative crew booking agency connecting international productions with experienced South African crew members.', 'South Africa', 'Cape Town', NULL, 'approved'),
('Lew Gillenson & Associates', 'agency', 'Sales Agent', 'South African sales agent handling international distribution for African feature films and documentaries.', 'South Africa', 'Johannesburg', NULL, 'approved'),
('Cinephil (SA Rep)', 'agency', 'Sales Agent', 'International sales agent with strong African film catalogue. Handles festival strategy and global distribution for SA films.', 'South Africa', 'Cape Town', 'https://www.cinephil.com', 'approved');

-- SOUTH AFRICA — Training
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, program_type, duration, cost, status) VALUES
('AFDA (The South African School of Motion Picture Medium and Live Performance)', 'training', 'Film School', 'South Africa''s leading film school with campuses in JHB, CPT, DBN, and PE. Offers BA and Honours degrees in film.', 'South Africa', 'Johannesburg', 'https://www.afda.co.za', 'school', '3-4 years (degree)', 'R60,000-R90,000/year', 'approved'),
('Big Fish School of Digital Filmmaking', 'training', 'Film School', 'Hands-on digital filmmaking school offering 1-2 year diplomas. Focus on practical production skills.', 'South Africa', 'Cape Town', 'https://www.bigfish.co.za', 'school', '1-2 years (diploma)', 'R40,000-R70,000/year', 'approved'),
('Realness Institute', 'training', 'Incubator', 'Pan-African creative residency and development lab for emerging filmmakers. Script development, directing, and producing labs.', 'South Africa', 'Johannesburg', 'https://www.realness.institute', 'mentorship', '2-12 weeks (residency)', 'Fully funded', 'approved'),
('The Animation School', 'training', 'Film School', 'Specialised animation training with 2D, 3D, and stop-motion programs. Produces industry-ready animators for Africa.', 'South Africa', 'Cape Town', 'https://www.theanimationschool.co.za', 'school', '1-3 years', 'R50,000-R80,000/year', 'approved'),
('Wits School of Arts — Film & Television', 'training', 'Film School', 'University of the Witwatersrand film department. BA, Honours, and MA in Film & Television. Strong academic and practical focus.', 'South Africa', 'Johannesburg', 'https://www.wits.ac.za/wsoa', 'school', '3-4 years (degree)', 'Varies (subsidised)', 'approved');


-- ============================================================
-- NIGERIA — Production Companies
-- ============================================================
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, speciality, notable_projects, year_founded, company_size, status) VALUES
('EbonyLife Studios', 'company', 'Fiction', 'Founded by Mo Abudu. Premium film and TV production powerhouse with a Netflix deal and EbonyLife Place entertainment complex.', 'Nigeria', 'Lagos', 'https://www.ebonylifetv.com', 'Feature Film, Television Series, Streaming', 'Chief Daddy, Castle & Castle, Blood Sisters (Netflix)', 2013, 'major', 'approved'),
('Inkblot Productions', 'company', 'Fiction', 'Leading commercial film production company. Consistent box office hits that blend Nollywood storytelling with global production values.', 'Nigeria', 'Lagos', 'https://www.inkblotproductions.com', 'Feature Film, Cinema Release', 'The Wedding Party, New Money, The Set Up', 2010, 'major', 'approved'),
('Kunle Afolayan Productions (KAP)', 'company', 'Fiction', 'Award-winning studio founded by Kunle Afolayan. Known for high-quality Nigerian features with international festival pedigree.', 'Nigeria', 'Lagos', 'https://www.kunleafolayan.com', 'Feature Film, Documentary, Series', 'October 1, Citation, Anikulapo (Netflix)', 2005, 'major', 'approved'),
('FilmOne Entertainment', 'company', 'Distribution', 'Nigeria''s leading film distribution and production company. Dominates Nollywood theatrical distribution and co-produces major titles.', 'Nigeria', 'Lagos', 'https://www.filmoneng.com', 'Distribution, Production, Cinema Exhibition', 'Distributed 60%+ of Nigerian box office hits', 2008, 'major', 'approved'),
('Anthill Studios', 'company', 'Animation', 'Nigeria''s leading animation and VFX studio. Creating world-class animated content from Africa for global audiences.', 'Nigeria', 'Abuja', 'https://www.anthillstudios.com', 'Animation, VFX, Gaming', 'Ladybug (animated series), VFX for Nollywood features', 2014, 'mid', 'approved'),
('Nemsia Films', 'company', 'Fiction', 'Independent production company led by Kemi Adetiba. Creates culturally impactful Nigerian stories with mainstream appeal.', 'Nigeria', 'Lagos', NULL, 'Feature Film, Television', 'King of Boys, King of Boys: The Return of the King (Netflix)', 2015, 'mid', 'approved'),
('Natives Media', 'company', 'Documentary', 'Documentary and unscripted content company telling untold Nigerian and African stories. Festival and streaming focus.', 'Nigeria', 'Lagos', NULL, 'Documentary, Unscripted, Short Film', 'Multiple AFRIFF and iREP selections', 2016, 'indie', 'approved'),
('Temple Productions', 'company', 'Fiction', 'Young, dynamic production company behind some of Nollywood''s recent critically acclaimed features and series.', 'Nigeria', 'Lagos', NULL, 'Feature Film, Series, Short Film', 'The Milkmaid (Nigeria''s Oscar submission), Voiceless', 2014, 'mid', 'approved'),
('Play Network Studios', 'company', 'Fiction', 'Fast-growing Nollywood production company creating commercial features and streaming content.', 'Nigeria', 'Lagos', 'https://www.playnetworkstudios.com', 'Feature Film, Streaming Content', 'Progressive Tailors Club, Passport', 2018, 'mid', 'approved'),
('Trino Studios', 'company', 'Co-Production', 'Lagos-based co-production company facilitating Nigeria-Europe and Nigeria-South Africa collaborations.', 'Nigeria', 'Lagos', NULL, 'Co-Production, Feature Film', 'Multiple cross-border African co-productions', 2017, 'indie', 'approved');

-- NIGERIA — Services
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, service_type, pricing_tier, status) VALUES
('Whiteplain Agency', 'service', 'Gear House', 'Leading equipment rental house in Lagos. Camera, lighting, grip, and production vehicle hire for features and commercials.', 'Nigeria', 'Lagos', 'https://www.whiteplainagency.com', 'Camera Rental, Lighting, Grip, Vehicles', 'mid', 'approved'),
('C & I Studios Lagos', 'service', 'Studio Space', 'Multi-purpose studio facility in Lagos with sound stages, green screen, and production offices for film and TV.', 'Nigeria', 'Lagos', NULL, 'Sound Stage, Green Screen, Production Office', 'mid', 'approved'),
('Mainland Studios', 'service', 'Studio Space', 'Modern studio facility on Lagos Mainland offering affordable stage space for Nollywood and commercial productions.', 'Nigeria', 'Lagos', NULL, 'Sound Stage, Production Space', 'budget', 'approved'),
('FilmHouse Cinemas', 'service', 'DCP & Deliverables', 'Nigeria''s largest cinema chain also provides DCP creation and theatrical deliverables services for local producers.', 'Nigeria', 'Lagos', 'https://www.filmhouseng.com', 'DCP, Cinema Distribution, QC', 'mid', 'approved'),
('Jungle Filmworks Post', 'service', 'Post-Production', 'Full post-production services: editing, color grading, sound design, and VFX for Nigerian features and series.', 'Nigeria', 'Lagos', NULL, 'Editing, Color Grading, Sound Design, VFX', 'mid', 'approved'),
('Mettlepost', 'service', 'Post-Production', 'Boutique post-production house offering color grading, online editing, and visual effects for premium Nollywood content.', 'Nigeria', 'Lagos', NULL, 'Color Grading, Online Edit, VFX', 'mid', 'approved'),
('SoundCity Studios', 'service', 'Sound Studio', 'Professional recording and sound mixing studio. ADR, Foley, and mixing for film and music productions.', 'Nigeria', 'Lagos', NULL, 'Sound Recording, ADR, Mixing', 'mid', 'approved'),
('Lagos Locations', 'service', 'Location Services', 'Location scouting and management across Lagos and South-West Nigeria. Permit facilitation and logistics.', 'Nigeria', 'Lagos', NULL, 'Location Scouting, Permits, Logistics', 'mid', 'approved'),
('Nile Casting', 'service', 'Casting', 'Professional casting service for film and TV productions in Nigeria. Maintains an extensive actor and extras database.', 'Nigeria', 'Lagos', NULL, 'Casting, Extras, Talent Search', 'mid', 'approved'),
('Subtitles Nigeria', 'service', 'Subtitling & Localization', 'Subtitling and localization services for Nollywood content. Yoruba, Igbo, Hausa, English, and international languages.', 'Nigeria', 'Lagos', NULL, 'Subtitling, Dubbing, Localization', 'budget', 'approved'),
('Kritica Productions', 'service', 'Permits & Fixers', 'Production fixing and permit facilitation for international productions shooting in Nigeria. Logistics, security, and local coordination.', 'Nigeria', 'Lagos', NULL, 'Fixing, Permits, Production Logistics', 'mid', 'approved');

-- NIGERIA — Agencies
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, status) VALUES
('Temple Management Company (TMC)', 'agency', 'Talent Agency', 'Nigeria''s largest talent management and booking agency. Represents A-list Nollywood actors and entertainers.', 'Nigeria', 'Lagos', 'https://www.templecompany.com', 'approved'),
('Urban Vision Agency', 'agency', 'Talent Agency', 'Talent representation agency for actors, models, and on-screen talent in the Nigerian entertainment industry.', 'Nigeria', 'Lagos', NULL, 'approved'),
('BluePrint Agency', 'agency', 'Crew Agency', 'Crew booking and production staffing agency. Connects international productions with experienced Nigerian crew.', 'Nigeria', 'Lagos', NULL, 'approved'),
('FilmKontrol', 'agency', 'Sales Agent', 'Nigerian-focused sales agency handling international distribution, festival strategy, and streaming deals for Nollywood films.', 'Nigeria', 'Lagos', NULL, 'approved'),
('Nollywood Bridge', 'agency', 'Co-Production Facilitator', 'Co-production facilitation company connecting Nigerian filmmakers with European and South African partners. Treaty navigation and funding assembly.', 'Nigeria', 'Lagos', NULL, 'approved');

-- NIGERIA — Training
INSERT INTO directory_listings (name, directory_type, category, description, country, city, website, program_type, duration, cost, status) VALUES
('Del-York Creative Academy', 'training', 'Film School', 'Nigeria''s premier film academy offering intensive filmmaking programs. Partnerships with New York Film Academy.', 'Nigeria', 'Lagos', 'https://www.delyorkcreativeacademy.com', 'school', '3-12 months', 'N500,000-N2,000,000', 'approved'),
('MultiChoice Talent Factory (West Africa Hub)', 'training', 'Incubator', 'Pan-African film training academy funded by MultiChoice. 12-month immersive program for emerging West African filmmakers.', 'Nigeria', 'Lagos', 'https://www.multichoicetalentfactory.com', 'school', '12 months', 'Fully funded', 'approved'),
('EbonyLife Creative Academy', 'training', 'Short Course', 'Industry-led workshops and masterclasses in screenwriting, directing, and producing. Run by EbonyLife Studios team.', 'Nigeria', 'Lagos', NULL, 'workshop', '1-4 weeks', 'Varies', 'approved'),
('AFRIFF Talent Hub', 'training', 'Masterclass', 'Annual masterclass program during the Africa International Film Festival. World-class instructors and industry mentorship.', 'Nigeria', 'Lagos', 'https://www.afriff.com', 'masterclass', '5 days (annual)', 'Included with AFRIFF pass', 'approved'),
('National Film Institute (NFI)', 'training', 'Film School', 'Federal government film training institution. Offers ND and HND in film production, cinematography, and editing.', 'Nigeria', 'Jos', 'https://www.nfi.gov.ng', 'school', '2-4 years (diploma/degree)', 'Subsidised', 'approved');
